### ISSUE TITLE
The app should not expect the messages to be in quotes

### ISSUE THREAD

**Issue by anandology** [AamAadmiParty/cleansweep-sms-bridge#2]
The cleansweep-sms-bridge expects the message to be of the form:

```
send-sms PLACE "message in quotes here"
```

What if the message sent by the user already has a quote?

It is better for the main function to take the first token as task and leave rest for that task to handle.

**Comment by raghavio** [comment]
Yes, I had this in mind. I was going to use to the split function instead.
Thanks.
